name: expense_manager
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.1.0
  pie_chart: ^5.4.0
  provider: ^6.1.2
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  sqflite_common_ffi: ^2.3.2+1

flutter:
  uses-material-design: true

  assets:
    - assets/SVGImages/food.svg
    - assets/SVGImages/wallet.svg
    - assets/SVGImages/medicine.svg
    - assets/SVGImages/movie.svg
    - assets/SVGImages/petrol.svg
    - assets/SVGImages/shopping.svg

    - assets/SVGImages/transaction.svg
    - assets/SVGImages/pie_chart.svg
    - assets/SVGImages/category.svg
    - assets/SVGImages/trash.svg
    - assets/SVGImages/person.svg
    - assets/SVGImages/dummy.svg
